// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {os} from '../models';

export function CreateFile():Promise<os.File>;

export function Greet(arg1:string):Promise<string>;

export function SaveNote(arg1:string,arg2:Array<Record<string, any>>):Promise<void>;
