// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function SaveAttachment(arg1) {
  return window['go']['main']['App']['SaveAttachment'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SendFile() {
  return window['go']['main']['App']['SendFile']();
}
