// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateFile() {
  return window['go']['main']['App']['CreateFile']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SaveTextNote(arg1) {
  return window['go']['main']['App']['SaveTextNote'](arg1);
}
