// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetFilePath():Promise<string>;

export function SaveAttachment(arg1:main.Thought):Promise<void>;

export function SaveNote(arg1:main.Thought):Promise<void>;
